### ISSUE TITLE
Support the `key` attribute in the sorting algorithms

### ISSUE THREAD

**Issue by nbro** [nbro/andz#76]
### TODO

- [ ] Support the `key` attribute in all sorting algorithms that can support this, like Python's built-in `sort` and `sorted` functions, which is used to sort the items according to this key, which should be a function
- [ ] Other functions, like `is_sorted`, should also support this
- [ ] Change the tests accordingly
