### ISSUE TITLE
Make sure the sorting algorithms are consistent with Python's built-in sorting functions

### ISSUE THREAD

**Issue by nbro** [nbro/andz#77]
### TODO

- [ ] Make sure the sorting algorithms are consistent with Python's built-in sorting functions `sort` and `sorted`
    - [ ] Find out which sorting algorithms should be consistent with the built-ins
       - For example, if both algorithms are stable, they should produce the same output
- [ ] Change tests accordingly
