### ISSUE TITLE
Support CI/CD for this project

### ISSUE THREAD

**Issue by nbro** [nbro/andz#79]
This project used to use Travis CI, but it is no longer free. I need to find a free alternative, as it's not worth paying for CI/CD for this project, which currently has not attracted many people.

### TODO

- [x] Find free CI/CD tools
- [ ] Choose the best one
- [ ] Support CI/CD with that tool
