### ISSUE TITLE
Use `pytest` instead of unittest

### ISSUE THREAD

**Issue by nbro** [nbro/andz#86]
### TODO

- [ ] Add the dependency pytest and other related dependencies that we may need .e.g. `pytest-cov`
- [ ] Convert the current tests to pytests
- [ ] Change the `Makefile` accordingly
- [ ] Update the docs
