### ISSUE TITLE
Implement matrix data structures

### ISSUE THREAD

**Issue by nbro** [nbro/andz#89]
### TODO

- [x] Implement the edge list representation
- [x] Implement the adjacency matrix representation
- [x] Implement the adjacency list representation
- [ ] Write the tests

### Questions

- Which matrices should we support?
- Should matrices derive from a `Graph` data structure?

### Ideas

- The implementations should be as simple as possible, as the goal is not provide optimized implementations, and they should illustrate the concepts
