### ISSUE TITLE
Add section on semantic versioning to the development section in the docs

### ISSUE THREAD

**Issue by nbro** [nbro/andz#91]
We should provide some guidelines on how to increase the versions after having made changes. We can also link to some site that describes semantic versioning more in detail.

### TODO

Explain how to increment the versions when

- [ ] some breaking change is introduced
- [ ] a new feature is introduced but no breaking change
- [ ] a bug is fixed (with or not breaking changes)
